#!/usr/bin/env bash
# a Bash script that configures a new Ubuntu machine to:
# install nginx
# Nginx should be listening on port 80
# When querying Nginx at its root / with a GET request (requesting a page) using curl, it must return a page that contains the string Hello World!

sudo apt update && sudo apt upgrade -y
sudo apt-get install -y nginx
echo "Hello World!" > /var/www/html/index.html
sudo service nginx restart
