#!/usr/bin/env bash
# a Bash script that configures a new Ubuntu machine to:
# install nginx
# Nginx should be listening on port 80
# When querying Nginx at its root / with a GET request (requesting a page) using curl, it must return a page that contains the string Hello World!

sudo apt update && sudo apt upgrade -y
sudo apt-get install -y nginx
sudo echo "Hello World!" | sudo tee /var/www/html/index.html
sudo sed -i '/listen 80 default_server;/a rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;' /etc/nginx/sites-enabled/default
sudo service nginx restart
