#!/usr/bin/env bash
# a Bash script that Configure your Nginx server to have a custom 404 page that contains the string Ceci n'est pas une page

sudo apt update && sudo apt upgrade -y
sudo apt-get install -y nginx
sudo echo "Hello World!" | sudo tee /var/www/html/index.html
sudo echo "Ceci n'est pas une page" | sudo tee /usr/share/nginx/html/custom_404.html
sudo sed -i '/listen 80 default_server;/a rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;' /etc/nginx/sites-enabled/default
sudo sed -i '/listen 80 default_server;/a error_page 404 /custom_404.html;\nlocation = /custom_404.html {\n\troot /usr/share/nginx/html;\n\tinternal;\n}' /etc/nginx/sites-enabled/default
sudo service nginx restart
