#!/usr/bin/env bash
# a Bash script that Configure HAproxy on your lb-01 server.

sudo apt update && sudo apt upgrade -y
sudo apt-get install --no-install-recommends software-properties-common -y
sudo add-apt-repository ppa:vbernat/haproxy-2.8 -y
sudo apt-get update
sudo apt-get install haproxy=2.8.\* -y
sudo sed -i -e '$afrontend http\n\tbind *:80\n\tdefault_backend web-backend\n\nbackend web-backend\n\tbalance roundrobin\n\tserver web1 54.236.44.154:80 check\n\tserver web2 54.237.5.182:80 check' /etc/haproxy/haproxy.cfg
sudo service haproxy restart
