#!/usr/bin/env bash
#  a Bash script that configures a server to make Nginx listen to port 80 and ipv4
sudo ln -sf /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
sudo service nginx restart
kill "$(pgrep 'nginx')"
