#!/usr/bin/env bash
#a Bash script that displays the visitor IP along with
#the HTTP status code from the Apache log file.
#then groups visitors by IP and HTTP status code, and displays this data

awk '{print $1 " " $9}' apache-access.log | sort | uniq -c | sort -rn
