#!/usr/bin/env bash
# a Bash script that configures the container
pkill apache2
sudo service nginx stop
sudo chown -R nginx:nginx /etc/nginx
chmod 777 /etc/nginx/nginx.conf
sudo sed -i 's/80/8080/g' /etc/nginx/sites-available/default
sudo sed -i '/#user www-data;/a \user nginx;' /etc/nginx/nginx.conf
sudo -u nginx service nginx start
